# Generated by Django 5.0 on 2023-12-19 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_brand_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Availability',
            field=models.CharField(choices=[('In stock', 'In stock'), ('Out of stock', 'Out of stock')], max_length=100, null=True),
        ),
    ]
