# Generated by Django 5.0 on 2023-12-23 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_product_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Availability',
            field=models.CharField(choices=[('В наличии', 'In stock'), ('Нет в наличии', 'Out of stock')], max_length=100, null=True),
        ),
    ]
